### ISSUE TITLE
Can't launch autoware with humble

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#2471]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I am preparing a new setup with ROS2 humble. For some reason, Autoware fails to launch for some weird argument substitution failure when I try:
```
$ ros2 launch autoware_launch planning_simulator.launch.xml map_path:=../data/autoware_data_universe/sample-map-planning/ vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit
```

Logs with `--debug`
```
[DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[INFO] [launch]: All log files can be found below /home/sig/.ros/log/2022-12-08-01-49-25-019569-vr-desktop-457560
[INFO] [launch]: Default logging verbosity is set to DEBUG
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f35ee31a050>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f35ee31a050>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7f35ee31b5e0>'
[DEBUG] [launch.launch_description_source]: Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_source.py", line 68, in try_get_launch_description_without_context
    perform_substitutions(context, self.__location)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_context.py", line 240, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/substitutions/launch_configuration.py", line 98, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: launch configuration 'vehicle_launch_pkg' does not exist

[DEBUG] [launch.launch_description_source]: Failed to load the launch file without a context: launch configuration 'vehicle_launch_pkg' does not exist
[DEBUG] [launch.launch_description_source]: Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_source.py", line 68, in try_get_launch_description_without_context
    perform_substitutions(context, self.__location)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_context.py", line 240, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/substitutions/launch_configuration.py", line 98, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: launch configuration 'sensor_launch_pkg' does not exist

[DEBUG] [launch.launch_description_source]: Failed to load the launch file without a context: launch configuration 'sensor_launch_pkg' does not exist
```

The logs says to the `sensor_launch_pkg` and `vehicle_launch_pkg` parameters are not set, but both are supposed to be set here:
https://github.com/autowarefoundation/autoware.universe/blob/01daebf42937a05a2d83f3dee2c0778389492e50/launch/tier4_sensing_launch/launch/sensing.launch.xml#L8
https://github.com/autowarefoundation/autoware.universe/blob/01daebf42937a05a2d83f3dee2c0778389492e50/launch/tier4_vehicle_launch/launch/vehicle.launch.xml#L10

And there are only use right after in their respective launch file.

Any idea?

### Expected behavior

No launch error

### Actual behavior

error

### Steps to reproduce

launch autoware

**Comment by kenji-miyake** [comment]
@VRichardJP Could you tell me the versions of each repository using `vcs export --exact src`? Are they the latest?

**Comment by VRichardJP** [comment]
It is on a fork of mine. The latest commit I have pulled is 41f47be4004bcf027d8c1188a6dbe7d8370f3287

But I don't have much changes in the launch files:
```
$ git diff origin/main --stat | grep "tier4_.*.launch.xml"                                                                                
 launch/tier4_map_launch/launch/map.launch.xml      |   14 +-
 .../tier4_sensing_launch/launch/sensing.launch.xml |    4 +
 .../tier4_system_launch/launch/system.launch.xml   |   34 +-
 .../tier4_vehicle_launch/launch/vehicle.launch.xml |    2 +-
```

```
diff --git a/launch/tier4_vehicle_launch/launch/vehicle.launch.xml b/launch/tier4_vehicle_launch/launch/vehicle.launch.xml
index 0493e1ae0..436a48aee 100644
--- a/launch/tier4_vehicle_launch/launch/vehicle.launch.xml
+++ b/launch/tier4_vehicle_launch/launch/vehicle.launch.xml
@@ -13,7 +13,7 @@
   <group>
     <arg name="model_file" default="$(find-pkg-share tier4_vehicle_launch)/urdf/vehicle.xacro" description="path to the file of model settings (*.xacro)"/>
     <node name="robot_state_publisher" pkg="robot_state_publisher" exec="robot_state_publisher">
-      <param name="robot_description" value="$(command 'xacro $(var model_file) vehicle_model:=$(var vehicle_model) sensor_model:=$(var sensor_model) config_dir:=$(var config_dir)' 'warn')"/>
+      <param name="robot_description" value="$(command 'xacro $(var model_file) vehicle_model:=$(var vehicle_model) sensor_model:=$(var sensor_model) config_dir:=$(var config_dir)')"/>
     </node>
   </group>
```
```
diff --git a/launch/tier4_sensing_launch/launch/sensing.launch.xml b/launch/tier4_sensing_launch/launch/sensing.launch.xml
index af9e4481a..3d15a8708 100644
--- a/launch/tier4_sensing_launch/launch/sensing.launch.xml
+++ b/launch/tier4_sensing_launch/launch/sensing.launch.xml
@@ -1,9 +1,11 @@
 <launch>
   <arg name="launch_driver" default="true" description="do launch driver"/>
   <arg name="sensor_model" default="sample_sensor_kit" description="sensor model name"/>
+  <arg name="vehicle_param_file" default="$(find-pkg-share vehicle_info_util)/config/vehicle_info.param.yaml" description="path to the file of vehicle info yaml"/>
   <arg name="vehicle_mirror_param_file" default="$(find-pkg-share vehicle_info_util)/config/vehicle_mirror.param.yaml" description="path to the file of vehicle mirror position yaml"/>
   <arg name="use_pointcloud_container" default="false" description="launch pointcloud container"/>
   <arg name="pointcloud_container_name" default="pointcloud_container"/>
+  <arg name="coordinate_system_param_file" default=""/>
 
   <let name="sensor_launch_pkg" value="$(find-pkg-share $(var sensor_model)_launch)"/>
 
@@ -13,9 +15,11 @@
     <!-- Driver -->
     <include file="$(var sensor_launch_pkg)/launch/sensing.launch.xml">
       <arg name="launch_driver" value="$(var launch_driver)"/>
+      <arg name="vehicle_param_file" value="$(var vehicle_param_file)"/>
       <arg name="vehicle_mirror_param_file" value="$(var vehicle_mirror_param_file)"/>
       <arg name="use_pointcloud_container" value="$(var use_pointcloud_container)"/>
       <arg name="pointcloud_container_name" value="$(var pointcloud_container_name)"/>
+      <arg name="coordinate_system_param_file" value="$(var coordinate_system_param_file)"/>
     </include>
   </group>
 </launch>
```

**Comment by kenji-miyake** [comment]
In addition to [autoware.universe](https://github.com/autowarefoundation/autoware.universe) itself, the consistency between repositories is important.
What are the versions of other repositories?

**Comment by VRichardJP** [comment]
This is the latest commits I have merged (`origin/main` is the original github branch for all my mirrors):
```
$ vcs custom src --args log origin/main -n 1
=== src/core/autoware.core (git) ===
commit 6bafedfb24fb34157ed65bfe3f6f4c1ed0fbc80b
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Thu Dec 1 23:12:15 2022 +0900

    ci(pre-commit): autoupdate (#62)
    
    updates:
    - [github.com/pre-commit/pre-commit-hooks: v4.3.0 → v4.4.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.3.0...v4.4.0)
    - [github.com/pre-commit/mirrors-prettier: v3.0.0-alpha.0 → v3.0.0-alpha.4](https://github.com/pre-commit/mirrors-prettier/compare/v3.0.0-alpha.0...v3.0.0-alpha.4)
    - [github.com/psf/black: 22.8.0 → 22.10.0](https://github.com/psf/black/compare/22.8.0...22.10.0)
    - [github.com/pre-commit/mirrors-clang-format: v14.0.6 → v15.0.4](https://github.com/pre-commit/mirrors-clang-format/compare/v14.0.6...v15.0.4)
    
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
=== src/core/autoware_adapi_msgs (git) ===
commit ee7384951bd02ddc5ed49151ad760034d2ad02bc
Author: Takagi, Isamu <43976882+isamu-takagi@users.noreply.github.com>
Date:   Wed Oct 26 11:15:35 2022 +0900

    feat(autoware_adapi_v1_msgs): add operation mode api message (#17)
    
    * feat(autoware_adapi_v1_msgs): add operation mode api message
    
    Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
    
    * feat: use minimum size type
    
    Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
    
    Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
=== src/core/autoware_common (git) ===
commit 518502a31c542b6a0966eb77d15bd4132aff97ac
Author: Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>
Date:   Thu Dec 1 22:30:03 2022 +0900

    ci: remove Galactic CI workflows (#136)
    
    Signed-off-by: Kenji Miyake <kenji.miyake@tier4.jp>
    
    Signed-off-by: Kenji Miyake <kenji.miyake@tier4.jp>
=== src/core/autoware_msgs (git) ===
commit 4f13d4b8b465ed7f424fce9af17882dbe1752875
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Thu Dec 1 23:07:38 2022 +0900

    ci(pre-commit): autoupdate (#31)
    
    updates:
    - [github.com/pre-commit/pre-commit-hooks: v4.3.0 → v4.4.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.3.0...v4.4.0)
    - [github.com/igorshubovych/markdownlint-cli: v0.32.1 → v0.32.2](https://github.com/igorshubovych/markdownlint-cli/compare/v0.32.1...v0.32.2)
    - [github.com/pre-commit/mirrors-prettier: v2.7.1 → v3.0.0-alpha.4](https://github.com/pre-commit/mirrors-prettier/compare/v2.7.1...v3.0.0-alpha.4)
    - [github.com/adrienverge/yamllint: v1.27.1 → v1.28.0](https://github.com/adrienverge/yamllint/compare/v1.27.1...v1.28.0)
    
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
=== src/core/external/autoware_auto_msgs (git) ===
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
=== src/launcher/autoware_launch (git) ===
commit 6cc94ee579391090140082be97877ef7d6f8393e
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Thu Dec 1 23:09:04 2022 +0900

    ci(pre-commit): autoupdate (#61)
    
    updates:
    - [github.com/pre-commit/pre-commit-hooks: v4.3.0 → v4.4.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.3.0...v4.4.0)
    - [github.com/igorshubovych/markdownlint-cli: v0.31.1 → v0.32.2](https://github.com/igorshubovych/markdownlint-cli/compare/v0.31.1...v0.32.2)
    - [github.com/pre-commit/mirrors-prettier: v2.7.1 → v3.0.0-alpha.4](https://github.com/pre-commit/mirrors-prettier/compare/v2.7.1...v3.0.0-alpha.4)
    - [github.com/adrienverge/yamllint: v1.26.3 → v1.28.0](https://github.com/adrienverge/yamllint/compare/v1.26.3...v1.28.0)
    - [github.com/psf/black: 22.6.0 → 22.10.0](https://github.com/psf/black/compare/22.6.0...22.10.0)
    
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
=== src/param/autoware_individual_params (git) ===
commit 79cff0ba014808050be6f5cb3b4764ba2c96c21c
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Thu Dec 1 23:06:25 2022 +0900

    ci(pre-commit): autoupdate (#35)
    
    updates:
    - [github.com/pre-commit/pre-commit-hooks: v4.3.0 → v4.4.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.3.0...v4.4.0)
    - [github.com/igorshubovych/markdownlint-cli: v0.31.1 → v0.32.2](https://github.com/igorshubovych/markdownlint-cli/compare/v0.31.1...v0.32.2)
    - [github.com/pre-commit/mirrors-prettier: v2.7.1 → v3.0.0-alpha.4](https://github.com/pre-commit/mirrors-prettier/compare/v2.7.1...v3.0.0-alpha.4)
    - [github.com/adrienverge/yamllint: v1.26.3 → v1.28.0](https://github.com/adrienverge/yamllint/compare/v1.26.3...v1.28.0)
    
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
=== src/sensor_component/external/sensor_component_description (git) ===
commit 475857daeb4c4883ab0295336713364b326e8278
Author: tier4-autoware-public-bot[bot] <98652886+tier4-autoware-public-bot[bot]@users.noreply.github.com>
Date:   Thu Dec 1 23:33:44 2022 +0900

    chore: sync files (#32)
    
    Signed-off-by: GitHub <noreply@github.com>
    
    Signed-off-by: GitHub <noreply@github.com>
    Co-authored-by: kenji-miyake <kenji-miyake@users.noreply.github.com>
=== src/sensor_kit/external/awsim_sensor_kit_launch (git) ===
commit 0d1276417b26d9d60be22b96a22c74a41e49e61c
Merge: a29a9ce 445fcc8
Author: Piotr Jaroszek <pijaro@users.noreply.github.com>
Date:   Mon Oct 3 08:48:11 2022 +0200

    Merge pull request #2 from RobotecAI/chore/distortion_filter_false
    
    chore(awsim_sensor_kit_launch): set use_distortion_corrector false
=== src/sensor_kit/sample_sensor_kit_launch (git) ===
commit ac88a926b1035204ecb35e6e9720453ec8451f55
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Fri Dec 2 10:38:16 2022 +0900

    ci(pre-commit): autoupdate (#40)
    
    updates:
    - [github.com/pre-commit/pre-commit-hooks: v4.3.0 → v4.4.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.3.0...v4.4.0)
    - [github.com/igorshubovych/markdownlint-cli: v0.31.1 → v0.32.2](https://github.com/igorshubovych/markdownlint-cli/compare/v0.31.1...v0.32.2)
    - [github.com/pre-commit/mirrors-prettier: v2.7.1 → v3.0.0-alpha.4](https://github.com/pre-commit/mirrors-prettier/compare/v2.7.1...v3.0.0-alpha.4)
    - [github.com/adrienverge/yamllint: v1.26.3 → v1.28.0](https://github.com/adrienverge/yamllint/compare/v1.26.3...v1.28.0)
    - [github.com/psf/black: 22.6.0 → 22.10.0](https://github.com/psf/black/compare/22.6.0...22.10.0)
    
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
=== src/universe/autoware.universe (git) ===
commit cd729c5904f29b5086a6983667b03a7e12be5a37
Author: Satoshi OTA <44889564+satoshi-ota@users.noreply.github.com>
Date:   Fri Dec 2 09:39:01 2022 +0900

    feat(avoidance): improve avoidance target filter (#2329)
    
    * feat(route_handler): add getMostLeftLanelet()
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
    
    * feat(avoidance): calc shiftable ratio in avoidance target filtering process
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
    
    * feat(avoidance): output object's debug info for rviz
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
    
    * fix(avoidance): use avoidance debug factor
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
    
    * feat(tier4_planning_launch): add new params for avoidance
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
    
    * fix(avoidance): reorder params for readability
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
    
    * fix(tier4_planning_launch): reorder params for readability
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
    
    Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>
=== src/universe/external/morai_msgs (git) ===
commit 6fd6a711e4bbf8a9989b54028e8074acabbbce6f
Merge: 6f89815 89a33ae
Author: shpark - MORAI Inc <92356892+Soohyeok-Park@users.noreply.github.com>
Date:   Mon Sep 19 17:25:33 2022 +0900

    Merge pull request #5 from Soohyeok-Park/main
    
    update msgs
=== src/universe/external/ros2bag_extensions (git) ===
commit cbd33e019ca6ebf9f3428397859e8af5bd593907
Author: Hayato Mizushima <hayato-m126@users.noreply.github.com>
Date:   Wed Oct 12 09:27:09 2022 +0900

    docs: update build command (#19)
=== src/universe/external/tier4_ad_api_adaptor (git) ===
commit ded3fcf35afcb5518c5bedecbe975228138768ae
Author: Takagi, Isamu <43976882+isamu-takagi@users.noreply.github.com>
Date:   Tue Nov 9 17:00:32 2021 +0900

    Add autoware api mapping system (#9)
    
    * Apply api mapping to engage
    
    * Fix format
    
    * Add vehicle status API (#8)
    
    * Add vehicle status API
    
    * Fix logging
    
    * Fix lint
    
    * Add vehicle command API (#11)
    
    * sync main for develop (#17)
    
    * Add CI (#12)
    
    * Add sync-public.yaml (#14)
    
    * Add sync-public.yaml
    
    Signed-off-by: Kenji Miyake <kenji.miyake@tier4.jp>
    
    * Add sync-public-develop.yaml
    
    Signed-off-by: Kenji Miyake <kenji.miyake@tier4.jp>
    
    * Change proposal sync app ID (#18)
    
    Signed-off-by: Kenji Miyake <kenji.miyake@tier4.jp>
    
    Co-authored-by: Takagi, Isamu <43976882+isamu-takagi@users.noreply.github.com>
    Co-authored-by: Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>
    
    * Add fail safe state API (#20)
    
    * Move autoware_api_utils
    
    * Move autoware_api_mapping
    
    * Fix package depend
    
    * Move autoware_api_generator
    
    Co-authored-by: autoware-iv-sync-ci[bot] <87871706+autoware-iv-sync-ci[bot]@users.noreply.github.com>
    Co-authored-by: Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>
=== src/universe/external/tier4_autoware_msgs (git) ===
commit 4d3f1ac0eddefecd5f36a868996b36b8dabde512
Author: taikitanaka3 <65527974+taikitanaka3@users.noreply.github.com>
Date:   Wed Nov 10 15:09:01 2021 +0900

    Revert "add VehicleEmergency (#55)" (#62)
    
    This reverts commit 072cc06996cade2bc29a3482cdc622c415f84558.
=== src/vehicle/external/pacmod3_msgs (git) ===
commit f16e787d5e3d32d0958c0346363501f0be449b2f
Author: icolwell-as <48106342+icolwell-as@users.noreply.github.com>
Date:   Mon Sep 13 16:02:53 2021 -0400

    1.0.0 Release (#4)
    
    * Add changelog
    
    * Fix changelog typo
=== src/vehicle/external/pacmod_interface (git) ===
commit e868133ea4ea7231d9c5e841f4b220b7dd9ceed4
Author: Takamasa Horibe <horibe.takamasa@gmail.com>
Date:   Thu Oct 20 16:08:45 2022 +0900

    refactor!: replace Tier4 ControlMode msg to auto_msg (#33)
    
    replace Tier4 ControlMode msg to auto_msg
    
    Signed-off-by: Takamasa Horibe <horibe.takamasa@gmail.com>
    
    Signed-off-by: Takamasa Horibe <horibe.takamasa@gmail.com>
=== src/vehicle/sample_vehicle_launch (git) ===
commit 21e38f88bcb9207ab401099617264154a70bb147
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Thu Dec 1 23:03:25 2022 +0900

    ci(pre-commit): autoupdate (#37)
    
    updates:
    - [github.com/pre-commit/pre-commit-hooks: v4.3.0 → v4.4.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.3.0...v4.4.0)
    - [github.com/igorshubovych/markdownlint-cli: v0.31.1 → v0.32.2](https://github.com/igorshubovych/markdownlint-cli/compare/v0.31.1...v0.32.2)
    - [github.com/pre-commit/mirrors-prettier: v2.7.1 → v3.0.0-alpha.4](https://github.com/pre-commit/mirrors-prettier/compare/v2.7.1...v3.0.0-alpha.4)
    - [github.com/adrienverge/yamllint: v1.26.3 → v1.28.0](https://github.com/adrienverge/yamllint/compare/v1.26.3...v1.28.0)
    - [github.com/psf/black: 22.6.0 → 22.10.0](https://github.com/psf/black/compare/22.6.0...22.10.0)
    
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

```

**Comment by kenji-miyake** [comment]
@VRichardJP I'm sorry I was unable to reproduce the problem.
Would it be possible for you to provide your .repos file so that others can test it easily?

Also, since it's probably not the bug of Autoware itself but maybe your fork or usage, is it okay to transfer this issue to the discussions?
If you want to keep this issue here, please provide more concrete steps to reproduce this issue.

**Comment by VRichardJP** [comment]
I'll try to reproduce with the original autoware. If it works I'll close this and investigate my fork on my own.

**Comment by VRichardJP** [comment]
I couldn't reproduce the problem with the same environment (docker, toolchain, etc) and latest autoware from github. Hopefully I will find the cause on my version.

**Comment by VRichardJP** [comment]
Quick update: there is no problem on my fork anymore either.
I did not change anything to the source code, so I am a bit puzzled. I just repulled the base humble docker image and re-run colcon.

`¯\_(ツ)_/¯`
