### ISSUE TITLE
`behavior_path_planner` crashes with `malloc_consolidate(): unaligned fastbin chunk detected` when new architecture is used

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#3148]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I know the new architecture is still WIP, but I got this crash while testing https://github.com/autowarefoundation/autoware.universe/pull/2933 on the new architecture (I don't think my changes are related).

While in the planning simulator, I set the goal pose multiple times and the `behavior_path_planner` crashed due to some bad memory alignment:
```
malloc_consolidate(): unaligned fastbin chunk detected

Thread 17 "component_conta" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd936d640 (LWP 406452)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140736837637696) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736837637696) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140736837637696) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736837637696, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7923476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff79097f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff796a6f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7abcb8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7981d7c in malloc_printerr (str=str@entry=0x7ffff7abf5d8 "malloc_consolidate(): unaligned fastbin chunk detected") at ./malloc/malloc.c:5664
#7  0x00007ffff7982a0c in malloc_consolidate (av=av@entry=0x7fffb4000030) at ./malloc/malloc.c:4750
#8  0x00007ffff7984c5b in _int_malloc (av=av@entry=0x7fffb4000030, bytes=bytes@entry=9073) at ./malloc/malloc.c:3965
#9  0x00007ffff7985c0a in _int_realloc (av=av@entry=0x7fffb4000030, oldp=oldp@entry=0x7fffb5073c30, oldsize=oldsize@entry=5392, nb=nb@entry=9088) at ./malloc/malloc.c:4878
#10 0x00007ffff79868e2 in __GI___libc_realloc (oldmem=0x7fffb5073c40, bytes=9080) at ./malloc/malloc.c:3494
#11 0x00007ffff7000d9f in eprosima::fastrtps::rtps::TopicPayloadPool::do_get_payload(unsigned int, eprosima::fastrtps::rtps::CacheChange_t&, bool) () at /opt/ros/humble/lib/libfastrtps.so.2.6
#12 0x00007ffff7066298 in eprosima::fastdds::dds::DataWriterImpl::perform_create_new_change(eprosima::fastrtps::rtps::ChangeKind_t, void*, eprosima::fastrtps::rtps::WriteParams&, eprosima::fastrtps::rtps::InstanceHandle_t const&) () at /opt/ros/humble/lib/libfastrtps.so.2.6
#13 0x00007ffff7067653 in eprosima::fastdds::dds::DataWriterImpl::create_new_change_with_params(eprosima::fastrtps::rtps::ChangeKind_t, void*, eprosima::fastrtps::rtps::WriteParams&) () at /opt/ros/humble/lib/libfastrtps.so.2.6
#14 0x00007ffff7067730 in eprosima::fastdds::dds::DataWriterImpl::create_new_change(eprosima::fastrtps::rtps::ChangeKind_t, void*) () at /opt/ros/humble/lib/libfastrtps.so.2.6
#15 0x00007ffff7067769 in eprosima::fastdds::dds::DataWriterImpl::write(void*) () at /opt/ros/humble/lib/libfastrtps.so.2.6
#16 0x00007ffff759f854 in rmw_fastrtps_shared_cpp::__rmw_publish(char const*, rmw_publisher_s const*, void const*, rmw_publisher_allocation_s*) () at /opt/ros/humble/lib/librmw_fastrtps_shared_cpp.so
#17 0x00007ffff78a2ade in  () at /opt/ros/humble/lib/librcl.so
#18 0x00007fffd35350b5 in rclcpp::Publisher<autoware_auto_planning_msgs::msg::PathWithLaneId_<std::allocator<void> >, std::allocator<void> >::do_inter_process_publish(autoware_auto_planning_msgs::msg::PathWithLaneId_<std::allocator<void> > const&) (msg=..., this=0x7fffc017e3f0) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#19 rclcpp::Publisher<autoware_auto_planning_msgs::msg::PathWithLaneId_<std::allocator<void> >, std::allocator<void> >::publish<autoware_auto_planning_msgs::msg::PathWithLaneId_<std::allocator<void> > >(autoware_auto_planning_msgs::msg::PathWithLaneId_<std::allocator<void> > const&) (this=0x7fffc017e3f0, msg=...) at /opt/ros/humble/include/rclcpp/rclcpp/publisher.hpp:297
#20 0x00007fffd34e2441 in behavior_path_planner::BehaviorPathPlannerNode::run() (this=0x7fffc0033d60) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#21 0x00007fffd34e67c5 in std::__invoke_impl<void, void (behavior_path_planner::BehaviorPathPlannerNode::*&)(), behavior_path_planner::BehaviorPathPlannerNode*&>(std::__invoke_memfun_deref, void (behavior_path_planner::BehaviorPathPlannerNode::*&)(), behavior_path_planner::BehaviorPathPlannerNode*&) (__t=@0x7fffc01b87a0: 0x7fffc0033d60, __f=@0x7fffc01b8790: (void (behavior_path_planner::BehaviorPathPlannerNode::*)(class behavior_path_planner::BehaviorPathPlannerNode * const)) 0x7fffd34e2090 <behavior_path_planner::BehaviorPathPlannerNode::run()>) at /usr/include/c++/11/bits/invoke.h:71
#22 std::__invoke<void (behavior_path_planner::BehaviorPathPlannerNode::*&)(), behavior_path_planner::BehaviorPathPlannerNode*&>(void (behavior_path_planner::BehaviorPathPlannerNode::*&)(), behavior_path_planner::BehaviorPathPlannerNode*&) (__fn=@0x7fffc01b8790: (void (behavior_path_planner::BehaviorPathPlannerNode::*)(class behavior_path_planner::BehaviorPathPlannerNode * const)) 0x7fffd34e2090 <behavior_path_planner::BehaviorPathPlannerNode::run()>) at /usr/include/c++/11/bits/invoke.h:96
#23 std::_Bind<void (behavior_path_planner::BehaviorPathPlannerNode::*(behavior_path_planner::BehaviorPathPlannerNode*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (__args=<optimized out>, this=0x7fffc01b8790) at /usr/include/c++/11/functional:420
#24 std::_Bind<void (behavior_path_planner::BehaviorPathPlannerNode::*(behavior_path_planner::BehaviorPathPlannerNode*))()>::operator()<, void>() (this=0x7fffc01b8790) at /usr/include/c++/11/functional:503
#25 rclcpp::GenericTimer<std::_Bind<void (behavior_path_planner::BehaviorPathPlannerNode::*(behavior_path_planner::BehaviorPathPlannerNode*))()>, (void*)0>::execute_callback_delegate<std::_Bind<void (behavior_path_planner::BehaviorPathPlannerNode::*(behavior_path_planner::BehaviorPathPlannerNode*))()>, (void*)0>() (this=0x7fffc01b8760) at /opt/ros/humble/include/rclcpp/rclcpp/timer.hpp:244
#26 rclcpp::GenericTimer<std::_Bind<void (behavior_path_planner::BehaviorPathPlannerNode::*(behavior_path_planner::BehaviorPathPlannerNode*))()>, (void*)0>::execute_callback() (this=0x7fffc01b8760) at /opt/ros/humble/include/rclcpp/rclcpp/timer.hpp:230
#27 0x00007ffff7e73651 in rclcpp::Executor::execute_any_executable(rclcpp::AnyExecutable&) () at /opt/ros/humble/lib/librclcpp.so
#28 0x00007ffff7e7a90a in rclcpp::executors::MultiThreadedExecutor::run(unsigned long) () at /opt/ros/humble/lib/librclcpp.so
#29 0x00007ffff7c052b3 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#30 0x00007ffff7975b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#31 0x00007ffff7a07a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 

```

### Expected behavior

no crash

### Actual behavior

crash

### Steps to reproduce

set goal multiple times in the planning simulator.

**Comment by VRichardJP** [comment]
I could reproduce on the main branch. The crash is sometimes different, but always from in RMW implementation:
```gdb
Thread 19 "component_conta" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd3fff640 (LWP 446658)]
0x00007ffff75ad9cf in rmw_fastrtps_shared_cpp::__rmw_wait(char const*, rmw_subscriptions_s*, rmw_guard_conditions_s*, rmw_services_s*, rmw_clients_s*, rmw_events_s*, rmw_wait_set_s*, rmw_time_s const*) () from /opt/ros/humble/lib/librmw_fastrtps_shared_cpp.so
(gdb) bt
#0  0x00007ffff75ad9cf in rmw_fastrtps_shared_cpp::__rmw_wait(char const*, rmw_subscriptions_s*, rmw_guard_conditions_s*, rmw_services_s*, rmw_clients_s*, rmw_events_s*, rmw_wait_set_s*, rmw_time_s const*) () at /opt/ros/humble/lib/librmw_fastrtps_shared_cpp.so
#1  0x00007ffff7604707 in rmw_wait () at /opt/ros/humble/lib/librmw_fastrtps_cpp.so
#2  0x00007ffff78aa718 in rcl_wait () at /opt/ros/humble/lib/librcl.so
#3  0x00007ffff7e70dbc in rclcpp::Executor::wait_for_work(std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () at /opt/ros/humble/lib/librclcpp.so
#4  0x00007ffff7e73ab3 in rclcpp::Executor::get_next_executable(rclcpp::AnyExecutable&, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () at /opt/ros/humble/lib/librclcpp.so
#5  0x00007ffff7e7a8e2 in rclcpp::executors::MultiThreadedExecutor::run(unsigned long) () at /opt/ros/humble/lib/librclcpp.so
#6  0x00007ffff7c052b3 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7975b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff7a07a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 
```
