### ISSUE TITLE
Many nodes crash instantly when `-fsanitize=address` is used

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#3400]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I compiled autoware with `-fsanitize=address -fno-omit-frame-pointer` flags. When I start autoware planning simulator, many nodes instantly crash with `new-delete-type-mismatch` error. For example:
```bash
$ /home/sig/autoware/install/component_interface_tools/lib/component_interface_tools/service_log_checker --ros-args -r __node:=service_log_checker -r __ns:=/system -p use_sim_time:=False -p wheel_radius:=0.383 -p wheel_width:=0.235 -p wheel_base:=2.79 -p wheel_tread:=1.64 -p front_overhang:=1.0 -p rear_overhang:=1.1 -p left_overhang:=0.128 -p right_overhang:=0.128 -p vehicle_height:=2.5 -p max_steer_angle:=0.7=================================================================
==44892==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x607000011040 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   72 bytes;
  size of the deallocated type: 1 bytes.
    #0 0x7fb29b31422f in operator delete(void*, unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x7fb29ac26dae in rcutils_string_map_fini (/opt/ros/humble/lib/librcutils.so+0x9dae)
    #2 0x7fb29af8c385  (/opt/ros/humble/lib/librcl.so+0x23385)
    #3 0x7fb29af8c6a7 in rcl_node_resolve_name (/opt/ros/humble/lib/librcl.so+0x236a7)
    #4 0x7fb29af8c878 in rcl_publisher_init (/opt/ros/humble/lib/librcl.so+0x23878)
    #5 0x7fb29b1bf8ad in rclcpp::PublisherBase::PublisherBase(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rosidl_message_type_support_t const&, rcl_publisher_options_s const&) (/opt/ros/humble/lib/librclcpp.so+0x1578ad)
    #6 0x7fb29b18380b  (/opt/ros/humble/lib/librclcpp.so+0x11b80b)
    #7 0x7fb29b183f40 in std::_Function_handler<std::shared_ptr<rclcpp::PublisherBase> (rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::QoS const&), rclcpp::create_publisher_factory<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::Publisher<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >(rclcpp::PublisherOptionsWithAllocator<std::allocator<void> > const&)::{lambda(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::QoS const&)#1}>::_M_invoke(std::_Any_data const&, rclcpp::node_interfaces::NodeBaseInterface*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::QoS const&) (/opt/ros/humble/lib/librclcpp.so+0x11bf40)
    #8 0x7fb29b1789a5 in rclcpp::node_interfaces::NodeParameters::NodeParameters(std::shared_ptr<rclcpp::node_interfaces::NodeBaseInterface>, std::shared_ptr<rclcpp::node_interfaces::NodeLoggingInterface>, std::shared_ptr<rclcpp::node_interfaces::NodeTopicsInterface>, std::shared_ptr<rclcpp::node_interfaces::NodeServicesInterface>, std::shared_ptr<rclcpp::node_interfaces::NodeClockInterface>, std::vector<rclcpp::Parameter, std::allocator<rclcpp::Parameter> > const&, bool, bool, rclcpp::QoS const&, rclcpp::PublisherOptionsBase const&, bool, bool) (/opt/ros/humble/lib/librclcpp.so+0x1109a5)
    #9 0x7fb29b1679cd in rclcpp::Node::Node(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&) (/opt/ros/humble/lib/librclcpp.so+0xff9cd)
    #10 0x7fb29b168207 in rclcpp::Node::Node(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&) (/opt/ros/humble/lib/librclcpp.so+0x100207)
    #11 0x557f135ef6e5 in ServiceLogChecker::ServiceLogChecker() /home/sig/autoware/src/universe/autoware.universe/common/component_interface_tools/src/service_log_checker.cpp:25
    #12 0x557f136f1529 in void __gnu_cxx::new_allocator<ServiceLogChecker>::construct<ServiceLogChecker>(ServiceLogChecker*) /usr/include/c++/11/ext/new_allocator.h:160
    #13 0x557f136f1529 in void std::allocator_traits<std::allocator<ServiceLogChecker> >::construct<ServiceLogChecker>(std::allocator<ServiceLogChecker>&, ServiceLogChecker*) /usr/include/c++/11/bits/alloc_traits.h:516
    #14 0x557f136f1529 in std::_Sp_counted_ptr_inplace<ServiceLogChecker, std::allocator<ServiceLogChecker>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<>(std::allocator<ServiceLogChecker>) /usr/include/c++/11/bits/shared_ptr_base.h:519
    #15 0x557f136f1529 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<ServiceLogChecker, std::allocator<ServiceLogChecker>>(ServiceLogChecker*&, std::_Sp_alloc_shared_tag<std::allocator<ServiceLogChecker> >) /usr/include/c++/11/bits/shared_ptr_base.h:650
    #16 0x557f136f1529 in std::__shared_ptr<ServiceLogChecker, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<ServiceLogChecker>>(std::_Sp_alloc_shared_tag<std::allocator<ServiceLogChecker> >) /usr/include/c++/11/bits/shared_ptr_base.h:1342
    #17 0x557f136f1529 in std::shared_ptr<ServiceLogChecker>::shared_ptr<std::allocator<ServiceLogChecker>>(std::_Sp_alloc_shared_tag<std::allocator<ServiceLogChecker> >) /usr/include/c++/11/bits/shared_ptr.h:409
    #18 0x557f136f1529 in std::shared_ptr<ServiceLogChecker> std::allocate_shared<ServiceLogChecker, std::allocator<ServiceLogChecker>>(std::allocator<ServiceLogChecker> const&) /usr/include/c++/11/bits/shared_ptr.h:863
    #19 0x557f136f1529 in std::shared_ptr<ServiceLogChecker> std::make_shared<ServiceLogChecker>() /usr/include/c++/11/bits/shared_ptr.h:879
    #20 0x557f135ddeb2 in main /home/sig/autoware/src/universe/autoware.universe/common/component_interface_tools/src/service_log_checker.cpp:105
    #21 0x7fb29a113d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #22 0x7fb29a113e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #23 0x557f135de3e4 in _start (/home/sig/autoware/build/component_interface_tools/service_log_checker+0x213e4)

0x607000011040 is located 0 bytes inside of 72-byte region [0x607000011040,0x607000011088)
allocated by thread T0 here:
    #0 0x7fb29b3131c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fb29ac26bb2 in rcutils_string_map_init (/opt/ros/humble/lib/librcutils.so+0x9bb2)

SUMMARY: AddressSanitizer: new-delete-type-mismatch ../../../../src/libsanitizer/asan/asan_new_delete.cpp:172 in operator delete(void*, unsigned long)
==44892==HINT: if you don't care about these errors you may set ASAN_OPTIONS=new_delete_type_mismatch=0
==44892==ABORTING
``` 

Don't know if it is a Autoware/ROS2 issue, nor if it is a big deal. In general it is a source of memory leak.

### Expected behavior

Should not crash

### Actual behavior

crashes

### Steps to reproduce

Start autoware

**Comment by VRichardJP** [comment]
The `new-delete-type-mismatch` could be a problem from ROS2 side: https://github.com/ros2/rclcpp/issues/2045
